version: "3"

services:
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  frontend:
    build: frontend
    container_name: nodejs
    volumes:
      - ./bundles:/frontend/bundles
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url "./"
    ports:
      - "3000:3000"
  
  backend:
    build: backend
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./bundles:/backend/bundles
      - ./media:/backend/media
      - ./backend:/backend
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db_data:

