version: "3"

services:
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build: ../frontend
    container_name: nodejs
    command: ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - bundles_volume:/frontend/bundles/.
    
  backend:
    build: ../backend
    container_name: django
    command: gunicorn -b 0.0.0.0:8000 star_burger.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - bundles_volume:/backend/bundles
      - ../backend/media:/backend/media
      - static_volume:/backend/static
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - ../backend/media:/media
    ports:
      - "80:80"
    depends_on:
      - backend 
    restart: always


volumes:
  db_data:
  static_volume:
  bundles_volume: